name: Build MyOS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            curl \
            xz-utils \
            tar \
            ca-certificates

      - name: Download static xbps
        run: |
          mkdir -p "$HOME/xbps"
          cd "$HOME/xbps"

          curl -LO \
            https://repo-default.voidlinux.org/static/xbps-static-latest.x86_64-musl.tar.xz

          tar -xf xbps-static-latest.x86_64-musl.tar.xz

      - name: Create rootfs
        run: |
          mkdir rootfs

          sudo "$HOME/xbps/usr/bin/xbps-install" \
            -r "$PWD/rootfs" \
            -S \
            -y \
            glibc \
            s6 \
            coreutils \
            dracut

      - name: Prepare filesystem
        run: |
          sudo mkdir -p \
            rootfs/{dev,proc,sys,run,tmp,etc,var,home,root,boot}

          sudo chmod 1777 rootfs/tmp

      - name: Inspect rootfs
        run: |
          sudo du -sh rootfs
          sudo find rootfs -maxdepth 2 -type d | sort

      - name: Create archive
        run: |
          sudo tar \
            --numeric-owner \
            -C rootfs \
            -czf myos-rootfs.tar.gz \
            .

      - name: Upload rootfs
        uses: actions/upload-artifact@v4
        with:
          name: myos-rootfs
          path: myos-rootfs.tar.gz
